#!/bin/sh

alias ll="ls -la"

DIR_CURRENT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR_CURRENT/.git-prompt.sh"
source "$DIR_CURRENT/.git-completion.bash"
GIT_PS1_SHOWDIRTYSTATE=true
export PS1='\[\033[32m\]\u@\h\[\033[00m\]:\[\033[32m\]\w\[\033[31m\]$(__git_ps1)\[\033[00m\] \n$ '
